"""Descriptors builtin — dados declarativos de todas as capabilities nativas.

Extraído de ``catalog.py`` para manter cada módulo abaixo de 300 linhas
(regra 14 do substrate).
"""

from __future__ import annotations

from .catalog import CapabilityDescriptor

BUILTIN_DESCRIPTORS: tuple[CapabilityDescriptor, ...] = (
    # ── Capabilities executáveis (core) ──
    CapabilityDescriptor(
        capability_id="search.public_web",
        family="search",
        fqn="arnaldo.capabilities.web_search.WebSearchCapability",
        name="Web Search",
        description="buscar informação atual na web — cotações, preços, câmbio, notícias, clima",
        requires_network=True,
        read_only=True,
        supports_live_lookup=True,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("lookup", "retrieve"),
        cost_profile="free",
        latency_profile="fast",
        locality="remote",
        access_mode="lookup",
        effect="read",
        freshness="current",
    ),
    CapabilityDescriptor(
        capability_id="connector.http.generic",
        family="connector",
        fqn="arnaldo.capabilities.http_connector.HttpConnectorCapability",
        name="HTTP Connector",
        description="requisições HTTP a APIs externas — GET, POST, REST, JSON",
        requires_network=True,
        read_only=False,
        supports_live_lookup=False,
        supports_inline=False,
        degrades_gracefully=False,
        preferred_intents=("retrieve", "mutate"),
        cost_profile="low",
        latency_profile="fast",
        locality="remote",
        access_mode="integration",
        effect="unknown",
        freshness="unknown",
    ),
    CapabilityDescriptor(
        capability_id="filesystem.local.search",
        family="filesystem",
        fqn="arnaldo.capabilities.filesystem_search.FilesystemSearchCapability",
        name="Filesystem Search",
        description="buscar arquivos e diretórios no filesystem local",
        requires_network=False,
        read_only=True,
        supports_live_lookup=False,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("lookup", "discover"),
        cost_profile="free",
        latency_profile="instant",
        locality="local",
        access_mode="discovery",
        effect="read",
        freshness="stable",
    ),
    CapabilityDescriptor(
        capability_id="shell.local.readonly",
        family="shell",
        fqn="arnaldo.capabilities.local_shell.LocalShellCapability",
        name="Local Shell (read-only)",
        description="executar comandos read-only no shell local",
        requires_network=False,
        read_only=True,
        supports_live_lookup=False,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("execute", "discover"),
        cost_profile="free",
        latency_profile="instant",
        locality="local",
        access_mode="command",
        effect="read",
        freshness="stable",
    ),
    # ── Capabilities builtin de domínio ──
    CapabilityDescriptor(
        capability_id="time.current",
        family="tool",
        fqn="arnaldo.capabilities.builtins.time_current.TimeCurrentCapability",
        name="Current Time",
        description="retornar data e hora atual em qualquer fuso horário",
        requires_network=False,
        read_only=True,
        supports_live_lookup=True,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("lookup",),
        cost_profile="free",
        latency_profile="instant",
        locality="local",
        access_mode="lookup",
        effect="read",
        freshness="current",
    ),
    CapabilityDescriptor(
        capability_id="http.readonly.fetch_json",
        family="connector",
        fqn="arnaldo.capabilities.builtins.http_json.HttpJsonCapability",
        name="HTTP JSON Fetch (read-only)",
        description="buscar dados JSON de API pública via GET — read-only",
        requires_network=True,
        read_only=True,
        supports_live_lookup=True,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("lookup", "retrieve"),
        cost_profile="free",
        latency_profile="fast",
        locality="remote",
        access_mode="lookup",
        effect="read",
        freshness="current",
    ),
    CapabilityDescriptor(
        capability_id="fx.rate",
        family="search",
        fqn="arnaldo.capabilities.builtins.live_domain.FxRateCapability",
        name="FX Rate",
        description="consultar cotação de câmbio entre moedas",
        requires_network=True,
        read_only=True,
        supports_live_lookup=True,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("lookup",),
        cost_profile="free",
        latency_profile="fast",
        locality="remote",
        access_mode="lookup",
        effect="read",
        freshness="current",
    ),
    CapabilityDescriptor(
        capability_id="weather.current",
        family="search",
        fqn="arnaldo.capabilities.builtins.live_domain.WeatherCurrentCapability",
        name="Weather Current",
        description="consultar clima atual de uma localidade",
        requires_network=True,
        read_only=True,
        supports_live_lookup=True,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("lookup",),
        cost_profile="free",
        latency_profile="fast",
        locality="remote",
        access_mode="lookup",
        effect="read",
        freshness="current",
    ),
    CapabilityDescriptor(
        capability_id="news.latest",
        family="search",
        fqn="arnaldo.capabilities.builtins.live_domain.NewsLatestCapability",
        name="Latest News",
        description="buscar notícias recentes sobre um tema",
        requires_network=True,
        read_only=True,
        supports_live_lookup=True,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("lookup", "retrieve"),
        cost_profile="free",
        latency_profile="fast",
        locality="remote",
        access_mode="lookup",
        effect="read",
        freshness="current",
    ),
    CapabilityDescriptor(
        capability_id="finance.quote",
        family="search",
        fqn="arnaldo.capabilities.builtins.live_domain.FinanceQuoteCapability",
        name="Finance Quote",
        description="consultar cotação de ação, ETF ou criptomoeda",
        requires_network=True,
        read_only=True,
        supports_live_lookup=True,
        supports_inline=True,
        degrades_gracefully=True,
        preferred_intents=("lookup",),
        cost_profile="free",
        latency_profile="fast",
        locality="remote",
        access_mode="lookup",
        effect="read",
        freshness="current",
    ),
    # ── Capabilities internas (orquestradoras, sem executor) ──
    CapabilityDescriptor(
        capability_id="intent.structure",
        family="intent",
        fqn="",
        name="Structure Intent",
        description="transformar pedido humano em contrato declarativo",
        internal=True,
        locality="internal",
        access_mode="orchestration",
        effect="orchestrate",
    ),
    CapabilityDescriptor(
        capability_id="work.decompose",
        family="work",
        fqn="",
        name="Decompose Work",
        description="quebrar trabalho em passos verificáveis",
        internal=True,
        locality="internal",
        access_mode="orchestration",
        effect="orchestrate",
    ),
    CapabilityDescriptor(
        capability_id="organization.generate",
        family="organization",
        fqn="",
        name="Generate Organization",
        description="criar organização temporária genérica",
        internal=True,
        locality="internal",
        access_mode="orchestration",
        effect="orchestrate",
    ),
    CapabilityDescriptor(
        capability_id="artifact.draft",
        family="artifact",
        fqn="",
        name="Draft Artifact",
        description="gerar artefato textual inicial",
        internal=True,
        locality="internal",
        access_mode="orchestration",
        effect="orchestrate",
    ),
    CapabilityDescriptor(
        capability_id="validation.critic_review",
        family="validation",
        fqn="",
        name="Critic Review",
        description="apontar lacunas e riscos",
        internal=True,
        locality="internal",
        access_mode="orchestration",
        effect="orchestrate",
    ),
    CapabilityDescriptor(
        capability_id="evidence.record",
        family="evidence",
        fqn="",
        name="Record Evidence",
        description="registrar eventos e decisões em ledger local",
        internal=True,
        locality="internal",
        access_mode="orchestration",
        effect="orchestrate",
    ),
)
